//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.31 at 08:54:53 PM CEST 
//


package com.tomveselka.uniconnector.isirWsdlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for isirWsCuzkStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="isirWsCuzkStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pocetVysledku" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="relevanceVysledku" type="{http://isirws.cca.cz/types/}relevanceType" minOccurs="0"/&gt;
 *         &lt;element name="casSynchronizace" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="kodChyby" type="{http://isirws.cca.cz/types/}kodChybyType" minOccurs="0"/&gt;
 *         &lt;element name="textChyby" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="popisChyby" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isirWsCuzkStatus", propOrder = {
    "pocetVysledku",
    "relevanceVysledku",
    "casSynchronizace",
    "kodChyby",
    "textChyby",
    "popisChyby"
})
public class IsirWsCuzkStatus {

    protected Integer pocetVysledku;
    protected Integer relevanceVysledku;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar casSynchronizace;
    @XmlSchemaType(name = "string")
    protected KodChybyType kodChyby;
    protected String textChyby;
    protected String popisChyby;

    /**
     * Gets the value of the pocetVysledku property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPocetVysledku() {
        return pocetVysledku;
    }

    /**
     * Sets the value of the pocetVysledku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPocetVysledku(Integer value) {
        this.pocetVysledku = value;
    }

    /**
     * Gets the value of the relevanceVysledku property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRelevanceVysledku() {
        return relevanceVysledku;
    }

    /**
     * Sets the value of the relevanceVysledku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRelevanceVysledku(Integer value) {
        this.relevanceVysledku = value;
    }

    /**
     * Gets the value of the casSynchronizace property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCasSynchronizace() {
        return casSynchronizace;
    }

    /**
     * Sets the value of the casSynchronizace property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCasSynchronizace(XMLGregorianCalendar value) {
        this.casSynchronizace = value;
    }

    /**
     * Gets the value of the kodChyby property.
     * 
     * @return
     *     possible object is
     *     {@link KodChybyType }
     *     
     */
    public KodChybyType getKodChyby() {
        return kodChyby;
    }

    /**
     * Sets the value of the kodChyby property.
     * 
     * @param value
     *     allowed object is
     *     {@link KodChybyType }
     *     
     */
    public void setKodChyby(KodChybyType value) {
        this.kodChyby = value;
    }

    /**
     * Gets the value of the textChyby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextChyby() {
        return textChyby;
    }

    /**
     * Sets the value of the textChyby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextChyby(String value) {
        this.textChyby = value;
    }

    /**
     * Gets the value of the popisChyby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopisChyby() {
        return popisChyby;
    }

    /**
     * Sets the value of the popisChyby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopisChyby(String value) {
        this.popisChyby = value;
    }

}
