//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.11 at 07:10:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://isirws.cca.cz/types/")
package com.tomveselka.uniconnector.isirWsdlClasses;
