//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.06 at 08:15:14 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Datová schránka subjektu, Typ_DS je dvoumístný \u010díselný kód jehož textový popis je v Nazev_typds
 * 
 * <p>Java class for datova_schranka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datova_schranka"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Priznak" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}priznak_ros"/&gt;
 *         &lt;element name="DS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}adresa_ds" minOccurs="0"/&gt;
 *         &lt;element name="Typ_DS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}popis" minOccurs="0"/&gt;
 *         &lt;element name="Nazev_typds" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}popis" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datova_schranka", propOrder = {
    "priznak",
    "ds",
    "typDS",
    "nazevTypds"
})
public class DatovaSchranka {

    @XmlElement(name = "Priznak")
    protected byte priznak;
    @XmlElement(name = "DS")
    protected String ds;
    @XmlElement(name = "Typ_DS")
    protected String typDS;
    @XmlElement(name = "Nazev_typds")
    protected String nazevTypds;

    /**
     * Gets the value of the priznak property.
     * 
     */
    public byte getPriznak() {
        return priznak;
    }

    /**
     * Sets the value of the priznak property.
     * 
     */
    public void setPriznak(byte value) {
        this.priznak = value;
    }

    /**
     * Gets the value of the ds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDS() {
        return ds;
    }

    /**
     * Sets the value of the ds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDS(String value) {
        this.ds = value;
    }

    /**
     * Gets the value of the typDS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypDS() {
        return typDS;
    }

    /**
     * Sets the value of the typDS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypDS(String value) {
        this.typDS = value;
    }

    /**
     * Gets the value of the nazevTypds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazevTypds() {
        return nazevTypds;
    }

    /**
     * Sets the value of the nazevTypds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazevTypds(String value) {
        this.nazevTypds = value;
    }

}
