//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 08:15:02 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stdadr_dotaz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stdadr_dotaz"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pomocne_ID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Typ_odkazu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Adresa_ARES" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}adresa_ARES" minOccurs="0"/&gt;
 *         &lt;element name="Stat" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_statu" minOccurs="0"/&gt;
 *         &lt;element name="Kraj" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_kraje" minOccurs="0"/&gt;
 *         &lt;element name="Okres" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_okresu" minOccurs="0"/&gt;
 *         &lt;element name="Obec" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_obce" minOccurs="0"/&gt;
 *         &lt;element name="PObvod" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_obce" minOccurs="0"/&gt;
 *         &lt;element name="Mestska_cast" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_mestske_casti" minOccurs="0"/&gt;
 *         &lt;element name="Cast_obce" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_casti_obce" minOccurs="0"/&gt;
 *         &lt;element name="Ulice" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_ulice" minOccurs="0"/&gt;
 *         &lt;element name="Cislo_do_adresy" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}cislo_do_adresy" minOccurs="0"/&gt;
 *         &lt;element name="Psc" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}psc" minOccurs="0"/&gt;
 *         &lt;element name="Adresa_textem" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}adresa_textem" minOccurs="0"/&gt;
 *         &lt;element name="Cestina" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}ano_ne" minOccurs="0"/&gt;
 *         &lt;element name="Jazyk" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}jazyk_odkazu" minOccurs="0"/&gt;
 *         &lt;element name="Typ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}ano_ne" minOccurs="0"/&gt;
 *         &lt;element name="Diakritika" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}ano_ne" minOccurs="0"/&gt;
 *         &lt;element name="Max_pocet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Redukce_slov" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}ano_ne" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stdadr_dotaz", propOrder = {
    "pomocneID",
    "typOdkazu",
    "adresaARES",
    "stat",
    "kraj",
    "okres",
    "obec",
    "pObvod",
    "mestskaCast",
    "castObce",
    "ulice",
    "cisloDoAdresy",
    "psc",
    "adresaTextem",
    "cestina",
    "jazyk",
    "typ",
    "diakritika",
    "maxPocet",
    "redukceSlov"
})
public class StdadrDotaz {

    @XmlElement(name = "Pomocne_ID")
    protected Integer pomocneID;
    @XmlElement(name = "Typ_odkazu")
    protected Integer typOdkazu;
    @XmlElement(name = "Adresa_ARES")
    protected AdresaARES adresaARES;
    @XmlElement(name = "Stat")
    protected String stat;
    @XmlElement(name = "Kraj")
    protected String kraj;
    @XmlElement(name = "Okres")
    protected String okres;
    @XmlElement(name = "Obec")
    protected String obec;
    @XmlElement(name = "PObvod")
    protected String pObvod;
    @XmlElement(name = "Mestska_cast")
    protected String mestskaCast;
    @XmlElement(name = "Cast_obce")
    protected String castObce;
    @XmlElement(name = "Ulice")
    protected String ulice;
    @XmlElement(name = "Cislo_do_adresy")
    protected String cisloDoAdresy;
    @XmlElement(name = "Psc")
    protected String psc;
    @XmlElement(name = "Adresa_textem")
    protected String adresaTextem;
    @XmlElement(name = "Cestina", defaultValue = "A")
    protected String cestina;
    @XmlElement(name = "Jazyk")
    @XmlSchemaType(name = "string")
    protected JazykOdkazu jazyk;
    @XmlElement(name = "Typ")
    protected String typ;
    @XmlElement(name = "Diakritika")
    protected String diakritika;
    @XmlElement(name = "Max_pocet", defaultValue = "20")
    protected Integer maxPocet;
    @XmlElement(name = "Redukce_slov", defaultValue = "N")
    protected String redukceSlov;

    /**
     * Gets the value of the pomocneID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPomocneID() {
        return pomocneID;
    }

    /**
     * Sets the value of the pomocneID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPomocneID(Integer value) {
        this.pomocneID = value;
    }

    /**
     * Gets the value of the typOdkazu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypOdkazu() {
        return typOdkazu;
    }

    /**
     * Sets the value of the typOdkazu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypOdkazu(Integer value) {
        this.typOdkazu = value;
    }

    /**
     * Gets the value of the adresaARES property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaARES }
     *     
     */
    public AdresaARES getAdresaARES() {
        return adresaARES;
    }

    /**
     * Sets the value of the adresaARES property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaARES }
     *     
     */
    public void setAdresaARES(AdresaARES value) {
        this.adresaARES = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the kraj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKraj() {
        return kraj;
    }

    /**
     * Sets the value of the kraj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKraj(String value) {
        this.kraj = value;
    }

    /**
     * Gets the value of the okres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkres() {
        return okres;
    }

    /**
     * Sets the value of the okres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkres(String value) {
        this.okres = value;
    }

    /**
     * Gets the value of the obec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObec() {
        return obec;
    }

    /**
     * Sets the value of the obec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObec(String value) {
        this.obec = value;
    }

    /**
     * Gets the value of the pObvod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPObvod() {
        return pObvod;
    }

    /**
     * Sets the value of the pObvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPObvod(String value) {
        this.pObvod = value;
    }

    /**
     * Gets the value of the mestskaCast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMestskaCast() {
        return mestskaCast;
    }

    /**
     * Sets the value of the mestskaCast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMestskaCast(String value) {
        this.mestskaCast = value;
    }

    /**
     * Gets the value of the castObce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCastObce() {
        return castObce;
    }

    /**
     * Sets the value of the castObce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCastObce(String value) {
        this.castObce = value;
    }

    /**
     * Gets the value of the ulice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUlice() {
        return ulice;
    }

    /**
     * Sets the value of the ulice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUlice(String value) {
        this.ulice = value;
    }

    /**
     * Gets the value of the cisloDoAdresy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCisloDoAdresy() {
        return cisloDoAdresy;
    }

    /**
     * Sets the value of the cisloDoAdresy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCisloDoAdresy(String value) {
        this.cisloDoAdresy = value;
    }

    /**
     * Gets the value of the psc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsc() {
        return psc;
    }

    /**
     * Sets the value of the psc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsc(String value) {
        this.psc = value;
    }

    /**
     * Gets the value of the adresaTextem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaTextem() {
        return adresaTextem;
    }

    /**
     * Sets the value of the adresaTextem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaTextem(String value) {
        this.adresaTextem = value;
    }

    /**
     * Gets the value of the cestina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCestina() {
        return cestina;
    }

    /**
     * Sets the value of the cestina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCestina(String value) {
        this.cestina = value;
    }

    /**
     * Gets the value of the jazyk property.
     * 
     * @return
     *     possible object is
     *     {@link JazykOdkazu }
     *     
     */
    public JazykOdkazu getJazyk() {
        return jazyk;
    }

    /**
     * Sets the value of the jazyk property.
     * 
     * @param value
     *     allowed object is
     *     {@link JazykOdkazu }
     *     
     */
    public void setJazyk(JazykOdkazu value) {
        this.jazyk = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyp(String value) {
        this.typ = value;
    }

    /**
     * Gets the value of the diakritika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiakritika() {
        return diakritika;
    }

    /**
     * Sets the value of the diakritika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiakritika(String value) {
        this.diakritika = value;
    }

    /**
     * Gets the value of the maxPocet property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxPocet() {
        return maxPocet;
    }

    /**
     * Sets the value of the maxPocet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxPocet(Integer value) {
        this.maxPocet = value;
    }

    /**
     * Gets the value of the redukceSlov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedukceSlov() {
        return redukceSlov;
    }

    /**
     * Sets the value of the redukceSlov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedukceSlov(String value) {
        this.redukceSlov = value;
    }

}
