//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.06 at 08:15:14 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * údaje o subjektu v RPSH
 * 
 * <p>Java class for subjekt_rpsh complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subjekt_rpsh"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Klic_ARES" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Klic_RPSH" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Ico" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}ico" minOccurs="0"/&gt;
 *         &lt;element name="Typ" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Datum_registrace" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Datum_aktualizace" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Cislo_registrace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Financni_urad_adr" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}financni_urad" minOccurs="0"/&gt;
 *         &lt;element name="Stav" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}stav_subjektu"/&gt;
 *         &lt;element name="Nazvy" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}nazvy_rpsh" minOccurs="0"/&gt;
 *         &lt;element name="Osoby" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}osoby_rpsh" minOccurs="0"/&gt;
 *         &lt;element name="Adresy" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}adresy_rpsh" minOccurs="0"/&gt;
 *         &lt;element name="Statutarni_organy" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}statut_organy_rpsh" minOccurs="0"/&gt;
 *         &lt;element name="Zmeny_stanov" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}zmeny_stanov_rpsh" minOccurs="0"/&gt;
 *         &lt;element name="Stavy_subjektu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}stavy_subj_rpsh" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subjekt_rpsh", propOrder = {
    "klicARES",
    "klicRPSH",
    "ico",
    "typ",
    "datumRegistrace",
    "datumAktualizace",
    "cisloRegistrace",
    "financniUradAdr",
    "stav",
    "nazvy",
    "osoby",
    "adresy",
    "statutarniOrgany",
    "zmenyStanov",
    "stavySubjektu"
})
public class SubjektRpsh {

    @XmlElement(name = "Klic_ARES")
    protected Integer klicARES;
    @XmlElement(name = "Klic_RPSH")
    protected Integer klicRPSH;
    @XmlElement(name = "Ico")
    protected String ico;
    @XmlElement(name = "Typ")
    protected Byte typ;
    @XmlElement(name = "Datum_registrace")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRegistrace;
    @XmlElement(name = "Datum_aktualizace")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumAktualizace;
    @XmlElement(name = "Cislo_registrace")
    protected String cisloRegistrace;
    @XmlElement(name = "Financni_urad_adr")
    protected FinancniUrad financniUradAdr;
    @XmlElement(name = "Stav", required = true)
    @XmlSchemaType(name = "string")
    protected StavSubjektu stav;
    @XmlElement(name = "Nazvy")
    protected NazvyRpsh nazvy;
    @XmlElement(name = "Osoby")
    protected OsobyRpsh osoby;
    @XmlElement(name = "Adresy")
    protected AdresyRpsh adresy;
    @XmlElement(name = "Statutarni_organy")
    protected StatutOrganyRpsh statutarniOrgany;
    @XmlElement(name = "Zmeny_stanov")
    protected ZmenyStanovRpsh zmenyStanov;
    @XmlElement(name = "Stavy_subjektu")
    protected StavySubjRpsh stavySubjektu;

    /**
     * Gets the value of the klicARES property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKlicARES() {
        return klicARES;
    }

    /**
     * Sets the value of the klicARES property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKlicARES(Integer value) {
        this.klicARES = value;
    }

    /**
     * Gets the value of the klicRPSH property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKlicRPSH() {
        return klicRPSH;
    }

    /**
     * Sets the value of the klicRPSH property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKlicRPSH(Integer value) {
        this.klicRPSH = value;
    }

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIco() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIco(String value) {
        this.ico = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTyp(Byte value) {
        this.typ = value;
    }

    /**
     * Gets the value of the datumRegistrace property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRegistrace() {
        return datumRegistrace;
    }

    /**
     * Sets the value of the datumRegistrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRegistrace(XMLGregorianCalendar value) {
        this.datumRegistrace = value;
    }

    /**
     * Gets the value of the datumAktualizace property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumAktualizace() {
        return datumAktualizace;
    }

    /**
     * Sets the value of the datumAktualizace property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumAktualizace(XMLGregorianCalendar value) {
        this.datumAktualizace = value;
    }

    /**
     * Gets the value of the cisloRegistrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCisloRegistrace() {
        return cisloRegistrace;
    }

    /**
     * Sets the value of the cisloRegistrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCisloRegistrace(String value) {
        this.cisloRegistrace = value;
    }

    /**
     * Gets the value of the financniUradAdr property.
     * 
     * @return
     *     possible object is
     *     {@link FinancniUrad }
     *     
     */
    public FinancniUrad getFinancniUradAdr() {
        return financniUradAdr;
    }

    /**
     * Sets the value of the financniUradAdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancniUrad }
     *     
     */
    public void setFinancniUradAdr(FinancniUrad value) {
        this.financniUradAdr = value;
    }

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link StavSubjektu }
     *     
     */
    public StavSubjektu getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavSubjektu }
     *     
     */
    public void setStav(StavSubjektu value) {
        this.stav = value;
    }

    /**
     * Gets the value of the nazvy property.
     * 
     * @return
     *     possible object is
     *     {@link NazvyRpsh }
     *     
     */
    public NazvyRpsh getNazvy() {
        return nazvy;
    }

    /**
     * Sets the value of the nazvy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazvyRpsh }
     *     
     */
    public void setNazvy(NazvyRpsh value) {
        this.nazvy = value;
    }

    /**
     * Gets the value of the osoby property.
     * 
     * @return
     *     possible object is
     *     {@link OsobyRpsh }
     *     
     */
    public OsobyRpsh getOsoby() {
        return osoby;
    }

    /**
     * Sets the value of the osoby property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobyRpsh }
     *     
     */
    public void setOsoby(OsobyRpsh value) {
        this.osoby = value;
    }

    /**
     * Gets the value of the adresy property.
     * 
     * @return
     *     possible object is
     *     {@link AdresyRpsh }
     *     
     */
    public AdresyRpsh getAdresy() {
        return adresy;
    }

    /**
     * Sets the value of the adresy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresyRpsh }
     *     
     */
    public void setAdresy(AdresyRpsh value) {
        this.adresy = value;
    }

    /**
     * Gets the value of the statutarniOrgany property.
     * 
     * @return
     *     possible object is
     *     {@link StatutOrganyRpsh }
     *     
     */
    public StatutOrganyRpsh getStatutarniOrgany() {
        return statutarniOrgany;
    }

    /**
     * Sets the value of the statutarniOrgany property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatutOrganyRpsh }
     *     
     */
    public void setStatutarniOrgany(StatutOrganyRpsh value) {
        this.statutarniOrgany = value;
    }

    /**
     * Gets the value of the zmenyStanov property.
     * 
     * @return
     *     possible object is
     *     {@link ZmenyStanovRpsh }
     *     
     */
    public ZmenyStanovRpsh getZmenyStanov() {
        return zmenyStanov;
    }

    /**
     * Sets the value of the zmenyStanov property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZmenyStanovRpsh }
     *     
     */
    public void setZmenyStanov(ZmenyStanovRpsh value) {
        this.zmenyStanov = value;
    }

    /**
     * Gets the value of the stavySubjektu property.
     * 
     * @return
     *     possible object is
     *     {@link StavySubjRpsh }
     *     
     */
    public StavySubjRpsh getStavySubjektu() {
        return stavySubjektu;
    }

    /**
     * Sets the value of the stavySubjektu property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavySubjRpsh }
     *     
     */
    public void setStavySubjektu(StavySubjRpsh value) {
        this.stavySubjektu = value;
    }

}
