//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 08:15:02 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xslt_ks.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xslt_ks"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="klient"/&gt;
 *     &lt;enumeration value="server"/&gt;
 *     &lt;enumeration value="savexml"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "xslt_ks")
@XmlEnum
public enum XsltKs {

    @XmlEnumValue("klient")
    KLIENT("klient"),
    @XmlEnumValue("server")
    SERVER("server"),
    @XmlEnumValue("savexml")
    SAVEXML("savexml");
    private final String value;

    XsltKs(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XsltKs fromValue(String v) {
        for (XsltKs c: XsltKs.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
