//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 08:15:02 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Základní identifikační a alokační údaje ekonomického subjektu
 * 
 * <p>Java class for zakladni_udaje_RZP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zakladni_udaje_RZP"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Klic_ARES" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Stav" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}stav_rzp" minOccurs="0"/&gt;
 *         &lt;element name="Datum_zmeny" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}ico" minOccurs="0"/&gt;
 *         &lt;element name="Obchodni_firma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}obchodni_firma" minOccurs="0"/&gt;
 *         &lt;element name="Pravni_forma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}pravni_forma" minOccurs="0"/&gt;
 *         &lt;element name="Kod_statu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}kod_statu" minOccurs="0"/&gt;
 *         &lt;element name="Nazev_statu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}nazev_statu" minOccurs="0"/&gt;
 *         &lt;element name="Datum_konkurs" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Zivnostensky_urad" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}zivnostensky_urad" minOccurs="0"/&gt;
 *         &lt;element name="Financni_urad" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}financni_urad" minOccurs="0"/&gt;
 *         &lt;element name="Org_slozka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}obchodni_firma" minOccurs="0"/&gt;
 *         &lt;element name="Datum_doruceni" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Prvni_zivnost" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Posledni_zivnost" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Vsech_zivnosti" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Aktivnich_zivnosti" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Vsech_provozoven" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Aktivnich_provozoven" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}ano_ne" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zakladni_udaje_RZP", propOrder = {
    "klicARES",
    "stav",
    "datumZmeny",
    "ico",
    "obchodniFirma",
    "pravniForma",
    "kodStatu",
    "nazevStatu",
    "datumKonkurs",
    "zivnostenskyUrad",
    "financniUrad",
    "orgSlozka",
    "datumDoruceni",
    "prvniZivnost",
    "posledniZivnost",
    "vsechZivnosti",
    "aktivnichZivnosti",
    "vsechProvozoven",
    "aktivnichProvozoven"
})
public class ZakladniUdajeRZP {

    @XmlElement(name = "Klic_ARES")
    protected Integer klicARES;
    @XmlElement(name = "Stav")
    protected String stav;
    @XmlElement(name = "Datum_zmeny")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZmeny;
    @XmlElement(name = "ICO")
    protected String ico;
    @XmlElement(name = "Obchodni_firma")
    protected String obchodniFirma;
    @XmlElement(name = "Pravni_forma")
    protected PravniForma pravniForma;
    @XmlElement(name = "Kod_statu")
    protected String kodStatu;
    @XmlElement(name = "Nazev_statu")
    protected String nazevStatu;
    @XmlElement(name = "Datum_konkurs")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumKonkurs;
    @XmlElement(name = "Zivnostensky_urad")
    protected ZivnostenskyUrad zivnostenskyUrad;
    @XmlElement(name = "Financni_urad")
    protected FinancniUrad financniUrad;
    @XmlElement(name = "Org_slozka")
    protected String orgSlozka;
    @XmlElement(name = "Datum_doruceni")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDoruceni;
    @XmlElement(name = "Prvni_zivnost")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prvniZivnost;
    @XmlElement(name = "Posledni_zivnost")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar posledniZivnost;
    @XmlElement(name = "Vsech_zivnosti")
    protected Integer vsechZivnosti;
    @XmlElement(name = "Aktivnich_zivnosti")
    protected Integer aktivnichZivnosti;
    @XmlElement(name = "Vsech_provozoven")
    protected Integer vsechProvozoven;
    @XmlElement(name = "Aktivnich_provozoven")
    protected String aktivnichProvozoven;

    /**
     * Gets the value of the klicARES property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKlicARES() {
        return klicARES;
    }

    /**
     * Sets the value of the klicARES property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKlicARES(Integer value) {
        this.klicARES = value;
    }

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStav(String value) {
        this.stav = value;
    }

    /**
     * Gets the value of the datumZmeny property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZmeny() {
        return datumZmeny;
    }

    /**
     * Sets the value of the datumZmeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZmeny(XMLGregorianCalendar value) {
        this.datumZmeny = value;
    }

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICO() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICO(String value) {
        this.ico = value;
    }

    /**
     * Gets the value of the obchodniFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObchodniFirma() {
        return obchodniFirma;
    }

    /**
     * Sets the value of the obchodniFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObchodniFirma(String value) {
        this.obchodniFirma = value;
    }

    /**
     * Gets the value of the pravniForma property.
     * 
     * @return
     *     possible object is
     *     {@link PravniForma }
     *     
     */
    public PravniForma getPravniForma() {
        return pravniForma;
    }

    /**
     * Sets the value of the pravniForma property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravniForma }
     *     
     */
    public void setPravniForma(PravniForma value) {
        this.pravniForma = value;
    }

    /**
     * Gets the value of the kodStatu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodStatu() {
        return kodStatu;
    }

    /**
     * Sets the value of the kodStatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodStatu(String value) {
        this.kodStatu = value;
    }

    /**
     * Gets the value of the nazevStatu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazevStatu() {
        return nazevStatu;
    }

    /**
     * Sets the value of the nazevStatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazevStatu(String value) {
        this.nazevStatu = value;
    }

    /**
     * Gets the value of the datumKonkurs property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumKonkurs() {
        return datumKonkurs;
    }

    /**
     * Sets the value of the datumKonkurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumKonkurs(XMLGregorianCalendar value) {
        this.datumKonkurs = value;
    }

    /**
     * Gets the value of the zivnostenskyUrad property.
     * 
     * @return
     *     possible object is
     *     {@link ZivnostenskyUrad }
     *     
     */
    public ZivnostenskyUrad getZivnostenskyUrad() {
        return zivnostenskyUrad;
    }

    /**
     * Sets the value of the zivnostenskyUrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZivnostenskyUrad }
     *     
     */
    public void setZivnostenskyUrad(ZivnostenskyUrad value) {
        this.zivnostenskyUrad = value;
    }

    /**
     * Gets the value of the financniUrad property.
     * 
     * @return
     *     possible object is
     *     {@link FinancniUrad }
     *     
     */
    public FinancniUrad getFinancniUrad() {
        return financniUrad;
    }

    /**
     * Sets the value of the financniUrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancniUrad }
     *     
     */
    public void setFinancniUrad(FinancniUrad value) {
        this.financniUrad = value;
    }

    /**
     * Gets the value of the orgSlozka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgSlozka() {
        return orgSlozka;
    }

    /**
     * Sets the value of the orgSlozka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgSlozka(String value) {
        this.orgSlozka = value;
    }

    /**
     * Gets the value of the datumDoruceni property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDoruceni() {
        return datumDoruceni;
    }

    /**
     * Sets the value of the datumDoruceni property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDoruceni(XMLGregorianCalendar value) {
        this.datumDoruceni = value;
    }

    /**
     * Gets the value of the prvniZivnost property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrvniZivnost() {
        return prvniZivnost;
    }

    /**
     * Sets the value of the prvniZivnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrvniZivnost(XMLGregorianCalendar value) {
        this.prvniZivnost = value;
    }

    /**
     * Gets the value of the posledniZivnost property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPosledniZivnost() {
        return posledniZivnost;
    }

    /**
     * Sets the value of the posledniZivnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPosledniZivnost(XMLGregorianCalendar value) {
        this.posledniZivnost = value;
    }

    /**
     * Gets the value of the vsechZivnosti property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVsechZivnosti() {
        return vsechZivnosti;
    }

    /**
     * Sets the value of the vsechZivnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVsechZivnosti(Integer value) {
        this.vsechZivnosti = value;
    }

    /**
     * Gets the value of the aktivnichZivnosti property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAktivnichZivnosti() {
        return aktivnichZivnosti;
    }

    /**
     * Sets the value of the aktivnichZivnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAktivnichZivnosti(Integer value) {
        this.aktivnichZivnosti = value;
    }

    /**
     * Gets the value of the vsechProvozoven property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVsechProvozoven() {
        return vsechProvozoven;
    }

    /**
     * Sets the value of the vsechProvozoven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVsechProvozoven(Integer value) {
        this.vsechProvozoven = value;
    }

    /**
     * Gets the value of the aktivnichProvozoven property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAktivnichProvozoven() {
        return aktivnichProvozoven;
    }

    /**
     * Sets the value of the aktivnichProvozoven property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAktivnichProvozoven(String value) {
        this.aktivnichProvozoven = value;
    }

}
