//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 08:15:02 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Základní identifikační a alokační údaje ekonomického subjektu
 * 
 * <p>Java class for zakladni_udaje_RZZ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zakladni_udaje_RZZ"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}ico" minOccurs="0"/&gt;
 *         &lt;element name="Zaclenene_zarizeni" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Detasovane_pracoviste" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Druh_zarizeni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}obchodni_firma" minOccurs="0"/&gt;
 *         &lt;element name="Typ_ZZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}typ_zdravotnickeho_zarizeni" minOccurs="0"/&gt;
 *         &lt;element name="Financni_urad" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}financni_urad" minOccurs="0"/&gt;
 *         &lt;element name="Datum_vzniku" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Datum_zaniku" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zakladni_udaje_RZZ", propOrder = {
    "ico",
    "zacleneneZarizeni",
    "detasovanePracoviste",
    "druhZarizeni",
    "typZZ",
    "financniUrad",
    "datumVzniku",
    "datumZaniku"
})
public class ZakladniUdajeRZZ {

    @XmlElement(name = "ICO")
    protected String ico;
    @XmlElement(name = "Zaclenene_zarizeni")
    protected Short zacleneneZarizeni;
    @XmlElement(name = "Detasovane_pracoviste")
    protected Short detasovanePracoviste;
    @XmlElement(name = "Druh_zarizeni")
    protected String druhZarizeni;
    @XmlElement(name = "Typ_ZZ")
    protected TypZdravotnickehoZarizeni typZZ;
    @XmlElement(name = "Financni_urad")
    protected FinancniUrad financniUrad;
    @XmlElement(name = "Datum_vzniku")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumVzniku;
    @XmlElement(name = "Datum_zaniku")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZaniku;

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICO() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICO(String value) {
        this.ico = value;
    }

    /**
     * Gets the value of the zacleneneZarizeni property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getZacleneneZarizeni() {
        return zacleneneZarizeni;
    }

    /**
     * Sets the value of the zacleneneZarizeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setZacleneneZarizeni(Short value) {
        this.zacleneneZarizeni = value;
    }

    /**
     * Gets the value of the detasovanePracoviste property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDetasovanePracoviste() {
        return detasovanePracoviste;
    }

    /**
     * Sets the value of the detasovanePracoviste property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDetasovanePracoviste(Short value) {
        this.detasovanePracoviste = value;
    }

    /**
     * Gets the value of the druhZarizeni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDruhZarizeni() {
        return druhZarizeni;
    }

    /**
     * Sets the value of the druhZarizeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDruhZarizeni(String value) {
        this.druhZarizeni = value;
    }

    /**
     * Gets the value of the typZZ property.
     * 
     * @return
     *     possible object is
     *     {@link TypZdravotnickehoZarizeni }
     *     
     */
    public TypZdravotnickehoZarizeni getTypZZ() {
        return typZZ;
    }

    /**
     * Sets the value of the typZZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypZdravotnickehoZarizeni }
     *     
     */
    public void setTypZZ(TypZdravotnickehoZarizeni value) {
        this.typZZ = value;
    }

    /**
     * Gets the value of the financniUrad property.
     * 
     * @return
     *     possible object is
     *     {@link FinancniUrad }
     *     
     */
    public FinancniUrad getFinancniUrad() {
        return financniUrad;
    }

    /**
     * Sets the value of the financniUrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancniUrad }
     *     
     */
    public void setFinancniUrad(FinancniUrad value) {
        this.financniUrad = value;
    }

    /**
     * Gets the value of the datumVzniku property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVzniku() {
        return datumVzniku;
    }

    /**
     * Sets the value of the datumVzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVzniku(XMLGregorianCalendar value) {
        this.datumVzniku = value;
    }

    /**
     * Gets the value of the datumZaniku property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZaniku() {
        return datumZaniku;
    }

    /**
     * Sets the value of the datumZaniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZaniku(XMLGregorianCalendar value) {
        this.datumZaniku = value;
    }

}
