//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.20 at 08:15:02 PM CEST 
//


package com.tomveselka.uniconnector.aresXsdClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for zaznam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zaznam"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Shoda_ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}shoda_ICO" minOccurs="0"/&gt;
 *         &lt;element name="Shoda_RC" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}shoda_RC" minOccurs="0"/&gt;
 *         &lt;element name="Shoda_OF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}shoda_OF" minOccurs="0"/&gt;
 *         &lt;element name="Vyhledano_dle" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1}vyhledano_dle"/&gt;
 *         &lt;element name="Typ_registru" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}typ_registru"/&gt;
 *         &lt;element name="Datum_vzniku" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Datum_zaniku" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Datum_platnosti" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Pravni_forma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}pravni_forma"/&gt;
 *         &lt;element name="Obchodni_firma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}obchodni_firma"/&gt;
 *         &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}ico" minOccurs="0"/&gt;
 *         &lt;element name="Identifikace" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1}identifikace" minOccurs="0"/&gt;
 *         &lt;element name="Kod_FU" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}kod_fu" minOccurs="0"/&gt;
 *         &lt;element name="Priznaky_subjektu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4}priznaky_subjektu" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zaznam", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1", propOrder = {
    "shodaICO",
    "shodaRC",
    "shodaOF",
    "vyhledanoDle",
    "typRegistru",
    "datumVzniku",
    "datumZaniku",
    "datumPlatnosti",
    "pravniForma",
    "obchodniFirma",
    "ico",
    "identifikace",
    "kodFU",
    "priznakySubjektu"
})
public class Zaznam {

    @XmlElement(name = "Shoda_ICO")
    protected ShodaICO shodaICO;
    @XmlElement(name = "Shoda_RC")
    protected ShodaRC shodaRC;
    @XmlElement(name = "Shoda_OF")
    protected ShodaOF shodaOF;
    @XmlElement(name = "Vyhledano_dle", required = true)
    @XmlSchemaType(name = "string")
    protected VyhledanoDle vyhledanoDle;
    @XmlElement(name = "Typ_registru", required = true)
    protected TypRegistru typRegistru;
    @XmlElement(name = "Datum_vzniku")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumVzniku;
    @XmlElement(name = "Datum_zaniku")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZaniku;
    @XmlElement(name = "Datum_platnosti", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPlatnosti;
    @XmlElement(name = "Pravni_forma", required = true)
    protected PravniForma pravniForma;
    @XmlElement(name = "Obchodni_firma", required = true)
    protected String obchodniFirma;
    @XmlElement(name = "ICO")
    protected String ico;
    @XmlElement(name = "Identifikace")
    protected Identifikace identifikace;
    @XmlElement(name = "Kod_FU")
    protected Short kodFU;
    @XmlElement(name = "Priznaky_subjektu")
    protected String priznakySubjektu;

    /**
     * Gets the value of the shodaICO property.
     * 
     * @return
     *     possible object is
     *     {@link ShodaICO }
     *     
     */
    public ShodaICO getShodaICO() {
        return shodaICO;
    }

    /**
     * Sets the value of the shodaICO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShodaICO }
     *     
     */
    public void setShodaICO(ShodaICO value) {
        this.shodaICO = value;
    }

    /**
     * Gets the value of the shodaRC property.
     * 
     * @return
     *     possible object is
     *     {@link ShodaRC }
     *     
     */
    public ShodaRC getShodaRC() {
        return shodaRC;
    }

    /**
     * Sets the value of the shodaRC property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShodaRC }
     *     
     */
    public void setShodaRC(ShodaRC value) {
        this.shodaRC = value;
    }

    /**
     * Gets the value of the shodaOF property.
     * 
     * @return
     *     possible object is
     *     {@link ShodaOF }
     *     
     */
    public ShodaOF getShodaOF() {
        return shodaOF;
    }

    /**
     * Sets the value of the shodaOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShodaOF }
     *     
     */
    public void setShodaOF(ShodaOF value) {
        this.shodaOF = value;
    }

    /**
     * Gets the value of the vyhledanoDle property.
     * 
     * @return
     *     possible object is
     *     {@link VyhledanoDle }
     *     
     */
    public VyhledanoDle getVyhledanoDle() {
        return vyhledanoDle;
    }

    /**
     * Sets the value of the vyhledanoDle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VyhledanoDle }
     *     
     */
    public void setVyhledanoDle(VyhledanoDle value) {
        this.vyhledanoDle = value;
    }

    /**
     * Gets the value of the typRegistru property.
     * 
     * @return
     *     possible object is
     *     {@link TypRegistru }
     *     
     */
    public TypRegistru getTypRegistru() {
        return typRegistru;
    }

    /**
     * Sets the value of the typRegistru property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypRegistru }
     *     
     */
    public void setTypRegistru(TypRegistru value) {
        this.typRegistru = value;
    }

    /**
     * Gets the value of the datumVzniku property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVzniku() {
        return datumVzniku;
    }

    /**
     * Sets the value of the datumVzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVzniku(XMLGregorianCalendar value) {
        this.datumVzniku = value;
    }

    /**
     * Gets the value of the datumZaniku property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZaniku() {
        return datumZaniku;
    }

    /**
     * Sets the value of the datumZaniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZaniku(XMLGregorianCalendar value) {
        this.datumZaniku = value;
    }

    /**
     * Gets the value of the datumPlatnosti property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPlatnosti() {
        return datumPlatnosti;
    }

    /**
     * Sets the value of the datumPlatnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPlatnosti(XMLGregorianCalendar value) {
        this.datumPlatnosti = value;
    }

    /**
     * Gets the value of the pravniForma property.
     * 
     * @return
     *     possible object is
     *     {@link PravniForma }
     *     
     */
    public PravniForma getPravniForma() {
        return pravniForma;
    }

    /**
     * Sets the value of the pravniForma property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravniForma }
     *     
     */
    public void setPravniForma(PravniForma value) {
        this.pravniForma = value;
    }

    /**
     * Gets the value of the obchodniFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObchodniFirma() {
        return obchodniFirma;
    }

    /**
     * Sets the value of the obchodniFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObchodniFirma(String value) {
        this.obchodniFirma = value;
    }

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICO() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICO(String value) {
        this.ico = value;
    }

    /**
     * Gets the value of the identifikace property.
     * 
     * @return
     *     possible object is
     *     {@link Identifikace }
     *     
     */
    public Identifikace getIdentifikace() {
        return identifikace;
    }

    /**
     * Sets the value of the identifikace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifikace }
     *     
     */
    public void setIdentifikace(Identifikace value) {
        this.identifikace = value;
    }

    /**
     * Gets the value of the kodFU property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getKodFU() {
        return kodFU;
    }

    /**
     * Sets the value of the kodFU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setKodFU(Short value) {
        this.kodFU = value;
    }

    /**
     * Gets the value of the priznakySubjektu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriznakySubjektu() {
        return priznakySubjektu;
    }

    /**
     * Sets the value of the priznakySubjektu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriznakySubjektu(String value) {
        this.priznakySubjektu = value;
    }

}
